### ISSUE TITLE
error when preview is closed

### ISSUE THREAD

**Issue by stevekrouse** [stevekrouse/WoofJS#433]
There's a bug when the code is run but the preview tab is closed:

```
woof.js:356 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at http://woofjs.com/dist/woof.js:356:45
    at http://woofjs.com/dist/woof.js:278:7
    at Array.forEach (<anonymous>)
    at Woof.thisContext._runReadys (http://woofjs.com/dist/woof.js:277:25)
    at http://woofjs.com/dist/woof.js:329:17
```

**Comment by truthgoddess** [comment]
Could not recreate error. Woof did not throw errors when preview window was closed. Haven't seen this in class. Happy to reopen if someone sees this issue.

**Comment by stevekrouse** [comment]
The error appears in the developer console, so students don't see it. Still, it's sloppy and we should fix it at some point.
<img width="1803" alt="Screen Shot 2018-07-24 at 11 03 26 AM" src="https://user-images.githubusercontent.com/2288939/58701105-ba03c900-83aa-11e9-808b-59bfd791c1ee.png">

**Comment by truthgoddess** [comment]
Great. Thanks for reopening! I agree!

**Comment by truthgoddess** [comment]
I should have checked the console. Not sure what I was thinking. Will research issue further going forward.
